spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: employee
  application:
    name: employee-service

server:
  port: 8081
 
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/



management:
  endpoints:
    web:
      exposure:
        include:
        - info


springdoc:
  show-actuator: true

  